"""
Library for configuration checks.
"""

import json

def check_existing_configs(config_counter: int, cfg: dict, results_folder: str) -> int:
    """
    Check if current configuration already exists.

    config_counter: How many configurations have already been tested.
    
    cfg: Configuration dictionary generated by OpenTuner.
    
    results_folder: Folder where the configuration results have been stored.
    
    returns: True if config has been already tested, False otherwise.
    """
    # TODO: Make a hashmap for better performance
    for i in range(config_counter):
        # Load existing config file
        configuration = open(results_folder + '/config_' + str(i) +'/config.json')
        existing_cfg = json.load(configuration)
        # If config already tested return 1
        if existing_cfg == cfg:
            print('Current config has been tested. Skipping...')
            return 1

        configuration.close()

    print('Current config has not been tested. Continuing...')
    return 0
